print("Question 4")
print("What is Slipknot's ability")
print("Using a rope dart, which is a metal dart tied to a long rope")
print("Being able to climb anything.")
print("Being a very skilled soldier")
print("Being a very intense metal musician.")

print("Question 9")
print("How does Batman defeat Superman")
print("By convincing him to stand down")
print("By using Kryptonite gas")
print("By using a kryptonite spear")
print("By using Gotham's electrical grid")

print("Question 5")
print("What is Katana's superpower")
print("A- Having a burning blade")
print("B- Having a blade that seals the soul of its victims")
print("C- Having a blade that nulifies meta powers, such as those of the Flash, El Diablo or other human characters.")
print("D- Having your back.")
answer5=input()